//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.Appointments = new HashSet<Appointment>();
            this.BillingHistories = new HashSet<BillingHistory>();
            this.Complaints = new HashSet<Complaint>();
            this.InsuranceClaims = new HashSet<InsuranceClaim>();
            this.MedicalHistories = new HashSet<MedicalHistory>();
            this.Prescriptions = new HashSet<Prescription>();
        }
    
        public int PatientID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public string ContactInformation { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<BillingHistory> BillingHistories { get; set; }
        public virtual ICollection<Complaint> Complaints { get; set; }
        public virtual ICollection<InsuranceClaim> InsuranceClaims { get; set; }
        public virtual ICollection<MedicalHistory> MedicalHistories { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Prescription> Prescriptions { get; set; }
    }
}
