//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Admins = new HashSet<Admin>();
            this.Doctors = new HashSet<Doctor>();
            this.Notifications = new HashSet<Notification>();
            this.Patients = new HashSet<Patient>();
            this.Receptionists = new HashSet<Receptionist>();
        }
    
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
    
        public virtual ICollection<Admin> Admins { get; set; }
        public virtual ICollection<Doctor> Doctors { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<Patient> Patients { get; set; }
        public virtual ICollection<Receptionist> Receptionists { get; set; }
    }
}
